//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_MySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class inwarrecord
    {
        public string InWarNo { get; set; }
        public string PurOrderNO { get; set; }
        public string SupID { get; set; }
        public string SupName { get; set; }
        public Nullable<System.DateTime> InWarDate { get; set; }
        public string Contact { get; set; }
        public string Phone { get; set; }
        public string UpdateName { get; set; }
        public string WHName { get; set; }
    }
}
