//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_MySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class inwarrecorddtl
    {
        public string InWarNo { get; set; }
        public string PdtID { get; set; }
        public int SeqNo { get; set; }
        public string PdtType { get; set; }
        public string Spec { get; set; }
        public string MakeIn { get; set; }
        public string Unit { get; set; }
        public Nullable<float> PurPrice { get; set; }
        public Nullable<float> Num { get; set; }
    }
}
