//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_MySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mcustomer
    {
        public string CusID { get; set; }
        public string CusName { get; set; }
        public string Phone { get; set; }
        public string Contact { get; set; }
        public string Salesman { get; set; }
        public string Address { get; set; }
        public string DelRemark { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public string BusLic { get; set; }
        public string BankName1 { get; set; }
        public string BankAccNo1 { get; set; }
        public string BankName2 { get; set; }
        public string BankAccNo2 { get; set; }
        public string BankName3 { get; set; }
        public string BankAccNo3 { get; set; }
        public string CreateID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateID { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
