//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_MySQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Configuration;
    
    public partial class erpsEntities : DbContext
    {
        public erpsEntities()
            : base("name=erpsEntities")
        {
    		Database.SetInitializer<erpsEntities>(null);
    		string conStr = ConfigurationManager.AppSettings["DBCONNECTION"].ToString();
            conStr = ConnectionDB.Decrypt(conStr);
            this.Database.Connection.ConnectionString = conStr;// ConnectionDB.ConnectionString();	
    		this.Configuration.ProxyCreationEnabled  = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tpurorderdtl> tpurorderdtl { get; set; }
        public virtual DbSet<inwarrecorddtl> inwarrecorddtl { get; set; }
        public virtual DbSet<mcustomer> mcustomer { get; set; }
        public virtual DbSet<mcustomerprodprice> mcustomerprodprice { get; set; }
        public virtual DbSet<mproducttype> mproducttype { get; set; }
        public virtual DbSet<mwarehouse> mwarehouse { get; set; }
        public virtual DbSet<sfunction> sfunction { get; set; }
        public virtual DbSet<srole> srole { get; set; }
        public virtual DbSet<srolefunction> srolefunction { get; set; }
        public virtual DbSet<suserrole> suserrole { get; set; }
        public virtual DbSet<tpurorderatt> tpurorderatt { get; set; }
        public virtual DbSet<tsaleforcast> tsaleforcast { get; set; }
        public virtual DbSet<tsaleforcastatt> tsaleforcastatt { get; set; }
        public virtual DbSet<tsaleforcastdtl> tsaleforcastdtl { get; set; }
        public virtual DbSet<tsaleorder> tsaleorder { get; set; }
        public virtual DbSet<tsaleorderatt> tsaleorderatt { get; set; }
        public virtual DbSet<twhcheckrecorddtl> twhcheckrecorddtl { get; set; }
        public virtual DbSet<twhcheckrecords> twhcheckrecords { get; set; }
        public virtual DbSet<twhinventory> twhinventory { get; set; }
        public virtual DbSet<v_customerprodprice> v_customerprodprice { get; set; }
        public virtual DbSet<v_purorderdtl> v_purorderdtl { get; set; }
        public virtual DbSet<v_saleforcast> v_saleforcast { get; set; }
        public virtual DbSet<v_saleforcastdtl> v_saleforcastdtl { get; set; }
        public virtual DbSet<v_saleorder> v_saleorder { get; set; }
        public virtual DbSet<v_whinventory> v_whinventory { get; set; }
        public virtual DbSet<v_whinventoryquery> v_whinventoryquery { get; set; }
        public virtual DbSet<vwhinventorywarning> vwhinventorywarning { get; set; }
        public virtual DbSet<inwarrecord> inwarrecord { get; set; }
        public virtual DbSet<outwarrecorddtl> outwarrecorddtl { get; set; }
        public virtual DbSet<outwarrecord> outwarrecord { get; set; }
        public virtual DbSet<tpurorder> tpurorder { get; set; }
        public virtual DbSet<v_purorder> v_purorder { get; set; }
        public virtual DbSet<tsaleorderdtl> tsaleorderdtl { get; set; }
        public virtual DbSet<v_saleorderdtl> v_saleorderdtl { get; set; }
        public virtual DbSet<msupplier> msupplier { get; set; }
        public virtual DbSet<suser> suser { get; set; }
        public virtual DbSet<msupplierprodprice> msupplierprodprice { get; set; }
        public virtual DbSet<v_supplierprodprice> v_supplierprodprice { get; set; }
        public virtual DbSet<twhstockrecords> twhstockrecords { get; set; }
        public virtual DbSet<mcurrency> mcurrency { get; set; }
        public virtual DbSet<mproduct> mproduct { get; set; }
        public virtual DbSet<mproductatt> mproductatt { get; set; }
        public virtual DbSet<twhinventory_his> twhinventory_his { get; set; }
    }
}
