//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_MySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mproduct
    {
        public string PdtID { get; set; }
        public string PdtName { get; set; }
        public string PdtType { get; set; }
        public string Spec { get; set; }
        public string Unit { get; set; }
        public Nullable<float> PurPrice { get; set; }
        public Nullable<float> SalPrice { get; set; }
        public string MakeIn { get; set; }
        public string MgrInfo { get; set; }
        public string IO_Type { get; set; }
        public string PdtBarcode { get; set; }
        public string Manufacturer { get; set; }
        public string Brand { get; set; }
        public string PdtModel { get; set; }
        public Nullable<float> CostPrice { get; set; }
        public string CurrencyID { get; set; }
        public string Remark { get; set; }
        public string CreateID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateID { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
