//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_MySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class outwarrecorddtl
    {
        public string OutWarNo { get; set; }
        public string PdtId { get; set; }
        public int SeqNo { get; set; }
        public string PdtName { get; set; }
        public string Model { get; set; }
        public string MakeIn { get; set; }
        public string MgrInfo { get; set; }
        public string Spec { get; set; }
        public string Unit { get; set; }
        public Nullable<float> OrderNum { get; set; }
        public Nullable<float> Num { get; set; }
        public string Remark { get; set; }
    }
}
