//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_MySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpurorderdtl
    {
        public string PurOrderNO { get; set; }
        public int SeqNo { get; set; }
        public string SupID { get; set; }
        public string PdtID { get; set; }
        public Nullable<float> OrderNum { get; set; }
        public Nullable<float> DelNum { get; set; }
        public Nullable<float> LftNum { get; set; }
        public Nullable<float> UnitPrice { get; set; }
        public Nullable<float> TotalAmount { get; set; }
        public System.DateTime DelDate { get; set; }
        public string Remark { get; set; }
        public string State { get; set; }
        public string UpdateID { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
