//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_MySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsaleorderdtl
    {
        public string SaleOrderNO { get; set; }
        public int SeqNo { get; set; }
        public string SaleFocaNO { get; set; }
        public string CusID { get; set; }
        public string PdtID { get; set; }
        public string Model { get; set; }
        public string FocaMonth { get; set; }
        public Nullable<float> OrderNum { get; set; }
        public Nullable<float> DelNum { get; set; }
        public Nullable<float> LftNum { get; set; }
        public Nullable<float> OrderPrice { get; set; }
        public System.DateTime DelDate { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string State { get; set; }
        public string CreateID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
