//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_MySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsaleforcastatt
    {
        public string SaleFocaNO { get; set; }
        public string AttFileName { get; set; }
        public string Remark { get; set; }
        public string CreateID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
