//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_MySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class twhcheckrecorddtl
    {
        public string ChkNO { get; set; }
        public string PdtID { get; set; }
        public float InvNum { get; set; }
        public float RealNum { get; set; }
        public float DifNum { get; set; }
        public string AdjStatus { get; set; }
        public string Remark { get; set; }
        public string UpdateID { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
