//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_MySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class twhstockrecords
    {
        public string WHID { get; set; }
        public string AreaID { get; set; }
        public string PosiID { get; set; }
        public string PdtID { get; set; }
        public string No { get; set; }
        public Nullable<float> Num { get; set; }
        public string RefWHID { get; set; }
        public string RefAreaID { get; set; }
        public string RefPosiID { get; set; }
        public string OpeType { get; set; }
        public string PurOrderNO { get; set; }
        public string SaleOrderNO { get; set; }
        public Nullable<int> RefSeqNo { get; set; }
        public string State { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
