//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_MySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_whinventoryquery
    {
        public string PdtID { get; set; }
        public string PdtName { get; set; }
        public string PdtType { get; set; }
        public string PdtTypeName { get; set; }
        public string Spec { get; set; }
        public string Unit { get; set; }
        public string WHID { get; set; }
        public string WHName { get; set; }
        public Nullable<float> InvNum { get; set; }
    }
}
