//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_MySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwhinventorywarning
    {
        public string PdtID { get; set; }
        public string PdtName { get; set; }
        public string Spec { get; set; }
        public string Unit { get; set; }
        public double InvNum { get; set; }
        public Nullable<double> P_N { get; set; }
        public Nullable<double> P_N1 { get; set; }
        public Nullable<double> P_N2 { get; set; }
        public Nullable<double> P_N3 { get; set; }
        public Nullable<double> S_N { get; set; }
        public Nullable<double> S_N1 { get; set; }
        public Nullable<double> S_N2 { get; set; }
        public Nullable<double> S_N3 { get; set; }
        public Nullable<double> F_N { get; set; }
        public Nullable<double> F_N1 { get; set; }
        public Nullable<double> F_N2 { get; set; }
        public Nullable<double> F_N3 { get; set; }
        public double WN { get; set; }
        public double WN1 { get; set; }
        public double WN2 { get; set; }
        public double WN3 { get; set; }
    }
}
